development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 696250805146-es9ikhh86ujmq7aqa3j97ghd1s90r352.apps.googleusercontent.com
  google_client_secret: SpWMuUnbGS9QI1fhJatX7Fza
  google_calendar_id: inline@inline-205713.iam.gserviceaccount.com
  project_id: inline-205713
